name: flutter_via_file_example
description: Demonstrates how to use the flutter_via_file package.
publish_to: 'none'

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_remote_logger:
    path: ../
  firebase_core: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
